# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  structurizr-cli = {
    pname = "structurizr-cli";
    version = "1.20.0";
    src = fetchurl {
      url = "https://github.com/structurizr/cli/releases/download/v1.20.0/structurizr-cli-1.20.0.zip";
      sha256 = "sha256-0E1MIq7uzQT/G6cVSxTWq6nVEnQP91KTJwtFbyObjUs=";
    };
  };
}
