# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  yml2dot = {
    pname = "yml2dot";
    version = "0d15bbb983dc1b503efe21b6583cb1319adcbe15";
    src = fetchFromGitHub ({
      owner = "lucasepe";
      repo = "yml2dot";
      rev = "0d15bbb983dc1b503efe21b6583cb1319adcbe15";
      fetchSubmodules = false;
      sha256 = "sha256-Pbi62CZJGgus3wBiqQ5W3ipvUeQKHn1bDYJF6LElCH4=";
    });
  };
}
