# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  bafi = {
    pname = "bafi";
    version = "fc0252bf097e8e0bfb16c553e3e613023f3ff38a";
    src = fetchFromGitHub ({
      owner = "mmalcek";
      repo = "bafi";
      rev = "fc0252bf097e8e0bfb16c553e3e613023f3ff38a";
      fetchSubmodules = false;
      sha256 = "sha256-pJwab2XkhYT0CxLf1QPAfOkjld01Jthe9WZAnX4Z5zg=";
    });
  };
}
