# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bafi = {
    pname = "bafi";
    version = "f1ec2ef3213d8cfcee703d9fe86ad94825d72faf";
    src = fetchFromGitHub ({
      owner = "mmalcek";
      repo = "bafi";
      rev = "f1ec2ef3213d8cfcee703d9fe86ad94825d72faf";
      fetchSubmodules = false;
      sha256 = "sha256-xuiUQVecDcsZ9GGQbOA51XxDvr4LGOsj71hmfNllGkM=";
    });
    date = "2022-10-07";
  };
}
